services:
  goclaw:
    stop_grace_period: 60s
    build:
      context: .
      dockerfile: dockerfile
    image: craig:latest
    container_name: goclaw
    restart: unless-stopped
    volumes:
      - ${HOME}/goclaw-data:/goclaw-data
    extra_hosts:
      - "host.docker.internal:host-gateway"